apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: awpks
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: andy-pipeline-triggerbinding
      template:
        name: andy-pipeline-triggertemplate
