apiVersion: v1
kind: Service
metadata:
  labels:
    app: andy-pipeline
    app.kubernetes.io/instance: andy-pipeline
    app.kubernetes.io/name: andy-pipeline
  name: andy-pipeline
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: andy-pipeline
    app.kubernetes.io/name: andy-pipeline
  sessionAffinity: None
  type: ClusterIP
