apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-repo
data:
  branch: main
  host: github.com
  protocol: https
  repo: apac1-andy-gitops
  org: cloud-native-garage-method-cohort
  parentdir: bash -c 'echo qa/$(basename ${NAMESPACE} -dev)'
